/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_1s2020_py2_201800523;

import estructuras.libro;
import estructuras.nodoArbolAvl;
import estructuras.nodoArbolB;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author David
 */
public class Biblioteca extends javax.swing.JFrame implements ListSelectionListener {

    nodoArbolAvl[] cat;
    nodoArbolAvl nov;
    libro[] books;
    DefaultListModel<String> dm = new DefaultListModel<String>();

    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
	initComponents();

	setLocationRelativeTo(null);
	jList1.addListSelectionListener(this);
	cat = Global.Globales.arbolCategorias.listaCategorias();
	if (cat != null) {
	    for (int i = 0; i < cat.length; i++) {

		comboBox.addItem(cat[i]);

	    }
	}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBox = new JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(dm);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        autor = new javax.swing.JLabel();
        editorial = new javax.swing.JLabel();
        idioma = new javax.swing.JLabel();
        ano = new javax.swing.JLabel();
        edicion = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        dueno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campoISBN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Biblioteca");

        jLabel2.setText("Selecciona una categoria:");

        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("ISBN:");

        jLabel5.setText("Titulo:");

        jLabel6.setText("Autor:");

        jLabel7.setText("Editorial:");

        jLabel8.setText("Año:");

        jLabel9.setText("Edicion:");

        jLabel10.setText("Categoria:");

        jLabel11.setText("Idioma:");

        jLabel12.setText("Dueño:");

        isbn.setText(".");

        titulo.setText(".");

        autor.setText(".");

        editorial.setText(".");

        idioma.setText(".");

        ano.setText(".");

        edicion.setText(".");

        categoria.setText(".");

        dueno.setText(".");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campoISBN.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(categoria)
                                            .addComponent(edicion)
                                            .addComponent(ano)
                                            .addComponent(editorial)
                                            .addComponent(autor)
                                            .addComponent(titulo)
                                            .addComponent(isbn)
                                            .addComponent(idioma)
                                            .addComponent(dueno)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(campoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(isbn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(titulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editorial)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(idioma))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ano)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edicion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(categoria)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dueno))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(campoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
	nov = (nodoArbolAvl) comboBox.getSelectedItem();
	books = nov.librosCategoria.listaLibros();
	titulo.setText("");
	isbn.setText("");
	autor.setText("");
	editorial.setText("");
	ano.setText("");
	edicion.setText("");
	categoria.setText("");
	idioma.setText("");
	dueno.setText("");
	dm.clear();
	for (libro book : books) {
	    try {
		dm.addElement(Integer.toString(book.getIsbn()));
	    } catch (NullPointerException e) {
		// JOptionPane.showMessageDialog(null, "Algo Salio Mal...");
	    }

	}
	jList1.setSelectedIndex(-1);
	//nov.librosCategoria.atravesar();
    }//GEN-LAST:event_comboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	int busqueda = Integer.parseInt(campoISBN.getText());
	nodoArbolB temp = Global.Globales.arbolCategorias.search(busqueda);
	if (temp != null) {
	    int i = 0;
	    while (i < temp.cantidad && busqueda > temp.libros[i].isbn) {

		i++;
	    }

	    titulo.setText(temp.libros[i].getTitulo());
	    isbn.setText(Integer.toString(temp.libros[i].getIsbn()));
	    autor.setText(temp.libros[i].getAutor());
	    editorial.setText(temp.libros[i].getEditorial());
	    ano.setText(Integer.toString(temp.libros[i].getAno()));
	    edicion.setText(Integer.toString(temp.libros[i].getEdicion()));
	    categoria.setText(temp.libros[i].getCategoria());
	    idioma.setText(temp.libros[i].getIdioma());
	    dueno.setText(Integer.toString(temp.libros[i].getCarnetUsuarioAdd()));
	} else {

	}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void valueChanged(ListSelectionEvent e) {
	if (jList1.getSelectedIndex() != -1) {
	    System.out.println(Integer.parseInt(jList1.getSelectedValue()));
	    nodoArbolB temp = Global.Globales.arbolCategorias.buscar(nov.categoria).librosCategoria.buscar(Integer.parseInt(jList1.getSelectedValue()));

	    int i = 0;
	    while (i < temp.cantidad && Integer.parseInt(jList1.getSelectedValue()) > temp.libros[i].isbn) {

		i++;
	    }

	    titulo.setText(temp.libros[i].getTitulo());
	    isbn.setText(Integer.toString(temp.libros[i].getIsbn()));
	    autor.setText(temp.libros[i].getAutor());
	    editorial.setText(temp.libros[i].getEditorial());
	    ano.setText(Integer.toString(temp.libros[i].getAno()));
	    edicion.setText(Integer.toString(temp.libros[i].getEdicion()));
	    categoria.setText(temp.libros[i].getCategoria());
	    idioma.setText(temp.libros[i].getIdioma());
	    dueno.setText(Integer.toString(temp.libros[i].getCarnetUsuarioAdd()));
	}

    }

    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano;
    private javax.swing.JLabel autor;
    private javax.swing.JTextField campoISBN;
    private javax.swing.JLabel categoria;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel dueno;
    private javax.swing.JLabel edicion;
    private javax.swing.JLabel editorial;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel isbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
