/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_1s2020_py2_201800523;

import estructuras.libro;
import estructuras.nodoArbolAvl;
import java.io.*;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class misLibros extends javax.swing.JFrame {

    nuevoLibro nuevoLibro1;

    nodoArbolAvl[] cat;
    nodoArbolAvl nov;

    public misLibros() {
	initComponents();
	setLocationRelativeTo(null);

	cat = Global.Globales.arbolCategorias.listaCategorias();
	if (cat != null) {

	    for (int i = 0; i < cat.length; i++) {

		if (cat[i].carnetAutor == Global.Globales.usuarioActivo.getContenido().getCarnet()) {
		    comboBox.addItem(cat[i]);
		}
	    }
	}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBox = new JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton6.setText("Nuevo Libro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Cargar Libros");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Mis Libros");

        jLabel2.setText("Eliminar una categoria:");

        jLabel3.setText("Eliminar un libro:");

        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
	nuevoLibro1 = new nuevoLibro();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
	JFileChooser selector = new JFileChooser();
	selector.setDialogTitle("Datos de libros");
	selector.setMultiSelectionEnabled(false);

	FileNameExtensionFilter filtro = new FileNameExtensionFilter("json", "json");
	selector.setFileFilter(filtro);

	int abc = selector.showOpenDialog(this);
	File ti = selector.getSelectedFile();

	if (abc == JFileChooser.APPROVE_OPTION) {
	    try {

	    } catch (Exception ex) {
		System.out.println(ex.getMessage());
	    }
	}

	JSONParser parser = new JSONParser();

	try {
	    Object objeto = parser.parse(new InputStreamReader(new FileInputStream(ti), "UTF-8"));
	    JSONObject objetoJson = (JSONObject) objeto;
	    JSONArray arrayJson = (JSONArray) objetoJson.get("Libros");

	    for (int i = 0; i < arrayJson.size(); i++) {
		JSONObject temp = (JSONObject) arrayJson.get(i);
		libro nuevolibro = new libro();
		nuevolibro.setIsbn(Integer.parseInt(temp.get("ISBN").toString()));
		nuevolibro.setAno(Integer.parseInt(temp.get("Año").toString()));
		nuevolibro.setIdioma(temp.get("Idioma").toString());
		nuevolibro.setTitulo(temp.get("Titulo").toString());
		nuevolibro.setEditorial(temp.get("Editorial").toString());
		nuevolibro.setAutor(temp.get("Autor").toString());
		nuevolibro.setEdicion(Integer.parseInt(temp.get("Edicion").toString()));
		nuevolibro.setCarnetUsuarioAdd(Global.Globales.usuarioActivo.getContenido().getCarnet());
		System.out.println(Global.Globales.usuarioActivo.getContenido().getCarnet());
		String categoria = temp.get("Categoria").toString();
		nuevolibro.setCategoria(categoria);

		nodoArbolAvl nodo = Global.Globales.arbolCategorias.buscar(categoria);

		if (nodo != null) {// categoria existe
		    nodo.librosCategoria.insertar(nuevolibro);
		    nodo.cantidad++;
		    nodo.librosCategoria.cantidad++;

		} else {
		    Global.Globales.arbolCategorias.raiz = Global.Globales.arbolCategorias.insertar(Global.Globales.arbolCategorias.raiz, categoria,
			    Global.Globales.usuarioActivo.getContenido().getCarnet());
		    nodoArbolAvl nodoNew = Global.Globales.arbolCategorias.buscar(categoria);

		    nodoNew.librosCategoria.insertar(nuevolibro);
		    nodoNew.cantidad++;
		    nodoNew.librosCategoria.cantidad++;

		}

	    }

	    /*  for (int i = 0; i < cat.length; i++) {
                System.out.println(cat[i].categoria);
            }*/
	} catch (org.json.simple.parser.ParseException e) {

	} catch (IOException e) {

	}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
	nov = (nodoArbolAvl) comboBox.getSelectedItem();
	libro[] books = nov.librosCategoria.listaLibros();

	//nov.librosCategoria.atravesar();
    }//GEN-LAST:event_comboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new misLibros().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
