/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_1s2020_py2_201800523;

import estructuras.libro;
import estructuras.nodoArbolAvl;
import java.io.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class misLibros extends javax.swing.JFrame {

    nuevoLibro nuevoLibro1;
    nodoArbolAvl[] cat;

    public misLibros() {
	initComponents();
	setLocationRelativeTo(null);
	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton6.setText("NUevo Libro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Cargar Libros");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton5)
                .addGap(64, 64, 64)
                .addComponent(jButton6)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(196, 196, 196))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
	nuevoLibro1 = new nuevoLibro();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
	JFileChooser selector = new JFileChooser();
	selector.setDialogTitle("Datos de libros");
	selector.setMultiSelectionEnabled(false);

	FileNameExtensionFilter filtro = new FileNameExtensionFilter("json", "json");
	selector.setFileFilter(filtro);

	int abc = selector.showOpenDialog(this);
	File ti = selector.getSelectedFile();

	if (abc == JFileChooser.APPROVE_OPTION) {
	    try {

	    } catch (Exception ex) {
		System.out.println(ex.getMessage());
	    }
	}

	JSONParser parser = new JSONParser();

	try {
	    Object objeto = parser.parse(new InputStreamReader(new FileInputStream(ti), "UTF-8"));
	    JSONObject objetoJson = (JSONObject) objeto;
	    JSONArray arrayJson = (JSONArray) objetoJson.get("Libros");

	    for (int i = 0; i < arrayJson.size(); i++) {
		JSONObject temp = (JSONObject) arrayJson.get(i);
		libro nuevolibro = new libro();
		nuevolibro.setIsbn(Integer.parseInt(temp.get("ISBN").toString()));
		nuevolibro.setAno(Integer.parseInt(temp.get("Año").toString()));
		nuevolibro.setIdioma(temp.get("Idioma").toString());
		nuevolibro.setTitulo(temp.get("Titulo").toString());
		nuevolibro.setEditorial(temp.get("Editorial").toString());
		nuevolibro.setAutor(temp.get("Autor").toString());
		nuevolibro.setEdicion(Integer.parseInt(temp.get("Edicion").toString()));
		nuevolibro.setCarnetUsuarioAdd(Global.Globales.usuarioActivo.getContenido().getCarnet());
		System.out.println(Global.Globales.usuarioActivo.getContenido().getCarnet());
		String categoria = temp.get("Categoria").toString();
		nuevolibro.setCategoria(categoria);

		nodoArbolAvl nodo = Global.Globales.arbolCategorias.buscar(categoria);

		if (nodo != null) {// categoria existe
		    nodo.librosCategoria.insertar(nuevolibro);
		    nodo.cantidad++;
		    nodo.librosCategoria.cantidad++;

		} else {
		    Global.Globales.arbolCategorias.raiz = Global.Globales.arbolCategorias.insertar(Global.Globales.arbolCategorias.raiz, categoria,
			    Global.Globales.usuarioActivo.getContenido().getCarnet());
		    nodoArbolAvl nodoNew = Global.Globales.arbolCategorias.buscar(categoria);
		    nodoNew.librosCategoria.insertar(nuevolibro);
		    nodoNew.cantidad++;
		    nodoNew.librosCategoria.cantidad++;

		}

	    }

	    /*  for (int i = 0; i < cat.length; i++) {
                System.out.println(cat[i].categoria);
            }*/
	} catch (org.json.simple.parser.ParseException e) {

	} catch (IOException e) {

	}
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(misLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new misLibros().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables
}
